# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.7.5-2-gafbd68b
_src_path: .
author_email: test@example.com
author_name: Test Author
backend_port: 5000
database_name: test-app
frontend_port: 3000
image_name: registry:5000/test-app
project_description: Test application
project_name: test-app
repo_url: https://github.com/test/test-app.git
s3_bucket_name: test-app-attachments
sse_gateway_port: 3002
testing_port_offset: 10
use_database: true
use_oidc: true
use_s3: true
use_sse: true
